CREATE TABLE `t_bot_config` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `config_key` varchar(128) NOT NULL,
  `config_value` varchar(512) NOT NULL,
  `value_type` varchar(32) NOT NULL,
  `remark` varchar(255) DEFAULT NULL,
  `enabled` tinyint NOT NULL DEFAULT 1,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_config_key` (`config_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `t_bot_runtime_state` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `symbol` varchar(32) NOT NULL,
  `stage` varchar(32) NOT NULL,
  `rule_type` varchar(32) DEFAULT NULL,
  `base_asset` varchar(32) DEFAULT NULL,
  `quote_asset` varchar(32) DEFAULT NULL,
  `buy_order_id` bigint DEFAULT NULL,
  `buy_client_order_id` varchar(64) DEFAULT NULL,
  `limit_buy_price` decimal(32,16) DEFAULT NULL,
  `sell_order_list_id` bigint DEFAULT NULL,
  `tp_order_id` bigint DEFAULT NULL,
  `sl_order_id` bigint DEFAULT NULL,
  `entry_price` decimal(32,16) DEFAULT NULL,
  `entry_qty` decimal(32,16) DEFAULT NULL,
  `entry_time` datetime DEFAULT NULL,
  `exit_expire_time` datetime DEFAULT NULL,
  `take_profit_price` decimal(32,16) DEFAULT NULL,
  `stop_loss_price` decimal(32,16) DEFAULT NULL,
  `h0` decimal(32,16) DEFAULT NULL,
  `l0` decimal(32,16) DEFAULT NULL,
  `r0` decimal(32,16) DEFAULT NULL,
  `p0` decimal(32,16) DEFAULT NULL,
  `invalidation_price` decimal(32,16) DEFAULT NULL,
  `trigger_time` datetime DEFAULT NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_symbol` (`symbol`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `t_bot_execution_log` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `symbol` varchar(32) NOT NULL,
  `high_price` decimal(32,16) DEFAULT NULL,
  `low_price` decimal(32,16) DEFAULT NULL,
  `current_price` decimal(32,16) DEFAULT NULL,
  `range_value` decimal(32,16) DEFAULT NULL,
  `rule3_upper_price` decimal(32,16) DEFAULT NULL,
  `middle_price` decimal(32,16) DEFAULT NULL,
  `invalidation_price` decimal(32,16) DEFAULT NULL,
  `volatility_percent` decimal(32,16) DEFAULT NULL,
  `decision` varchar(64) DEFAULT NULL,
  `met_reasons` text,
  `unmet_reasons` text,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_symbol_ct` (`symbol`,`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `t_bot_order_record` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `symbol` varchar(32) NOT NULL,
  `rule_type` varchar(32) DEFAULT NULL,
  `action_type` varchar(32) NOT NULL,
  `side` varchar(16) DEFAULT NULL,
  `order_type` varchar(32) DEFAULT NULL,
  `exchange_order_id` bigint DEFAULT NULL,
  `exchange_order_list_id` bigint DEFAULT NULL,
  `client_order_id` varchar(64) DEFAULT NULL,
  `price` decimal(32,16) DEFAULT NULL,
  `quantity` decimal(32,16) DEFAULT NULL,
  `quote_amount` decimal(32,16) DEFAULT NULL,
  `status` varchar(32) DEFAULT NULL,
  `request_json` text,
  `response_json` text,
  `remark` varchar(255) DEFAULT NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_symbol_ct` (`symbol`,`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `t_bot_position` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `symbol` varchar(32) NOT NULL,
  `rule_type` varchar(32) DEFAULT NULL,
  `entry_order_record_id` bigint DEFAULT NULL,
  `sell_order_list_id` bigint DEFAULT NULL,
  `tp_order_id` bigint DEFAULT NULL,
  `sl_order_id` bigint DEFAULT NULL,
  `entry_price` decimal(32,16) DEFAULT NULL,
  `entry_qty` decimal(32,16) DEFAULT NULL,
  `take_profit_price` decimal(32,16) DEFAULT NULL,
  `stop_loss_price` decimal(32,16) DEFAULT NULL,
  `entry_time` datetime DEFAULT NULL,
  `expire_time` datetime DEFAULT NULL,
  `status` varchar(32) NOT NULL,
  `close_price` decimal(32,16) DEFAULT NULL,
  `close_time` datetime DEFAULT NULL,
  `close_reason` varchar(64) DEFAULT NULL,
  `profit_amount` decimal(32,16) DEFAULT NULL,
  `profit_rate` decimal(32,16) DEFAULT NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_symbol_status` (`symbol`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `t_bot_event` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `symbol` varchar(32) NOT NULL,
  `event_type` varchar(64) NOT NULL,
  `event_message` varchar(500) NOT NULL,
  `payload_json` text,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_symbol_ct` (`symbol`,`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `t_bot_config` (`config_key`, `config_value`, `value_type`, `remark`, `enabled`) VALUES
('BOT_ENABLE', 'true', 'BOOLEAN', '总开关', 1),
('BINANCE_USE_TESTNET', 'true', 'BOOLEAN', '是否走Binance测试网', 1),
('BINANCE_API_KEY', 'replace_me', 'STRING', 'Binance API Key', 1),
('BINANCE_API_SECRET', 'replace_me', 'STRING', 'Binance API Secret', 1),
('BINANCE_RECV_WINDOW', '5000', 'NUMBER', 'Binance recvWindow', 1),
('BINANCE_SYMBOL', 'BTCUSDT', 'STRING', '交易对', 1),
('BINANCE_SINGLE_ORDER_U', '100', 'NUMBER', '单次下单金额，单位U', 1),
('BOT_RULE3_UPPER_RATIO', '0.25', 'NUMBER', '规则3上沿比例', 1),
('BOT_RULE4_MIDDLE_RATIO', '0.50', 'NUMBER', '规则4中点比例', 1),
('BOT_RULE4_INVALID_RATIO', '0.75', 'NUMBER', '规则4未成交失效比例', 1),
('BOT_RULE4_PULLBACK_RATE', '0.015', 'NUMBER', '规则4挂单回撤比例', 1),
('BOT_TAKE_PROFIT_RATE', '0.02', 'NUMBER', '止盈比例', 1),
('BOT_STOP_LOSS_RATE', '0.012', 'NUMBER', '止损比例', 1),
('BOT_STOP_LIMIT_GAP_RATE', '0.001', 'NUMBER', '止损限价比stop再低多少', 1),
('BOT_MIN_VOLATILITY_PERCENT', '1.5', 'NUMBER', '规则4最小波动百分比', 1);
